# Generated by Django 5.0 on 2023-12-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
    ]
