# Generated by Django 5.0 on 2023-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heroes", "0002_alter_group_unique_together_remove_group_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="hero",
            field=models.JSONField(),
        ),
    ]
